from app.model.usuario import Usuario
from app.model.paciente import Paciente
from app.model.historia import HistoriaClinica
from app.model.tratamiento import Tratamiento
from app.model.diente import Diente
from app.model.odontograma import Odontograma
from app.model.odontograma_detalle import OdontogramaDetalle
from app.model.meta import Meta
from app.model.meta_estudiante import MetaEstudiante
from app.model.profesor_estudiante import ProfesorEstudiante
